# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(max_length=13)),
                ('author_firstname', models.CharField(max_length=50)),
                ('author_middlename', models.CharField(max_length=50)),
                ('author_lastname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('juid', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('net_weight', models.IntegerField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='juid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='juid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='juid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='books',
            name='juid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
