# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='juid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.IntegerField(),
        ),
    ]
