# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170611_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='juid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cosmetics',
            old_name='juid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='juid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='juid',
            new_name='product',
        ),
    ]
